CREATE TABLE IF NOT EXISTS webdav_users (
   id INT AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(50) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL COMMENT '存储MD5加密后的密码',
   user_group VARCHAR(50) NOT NULL DEFAULT 'user' COMMENT '用户组/角色',
   status INT NOT NULL DEFAULT 0 COMMENT '用户状态：0-有效, 1-停用',
   webdav_token VARCHAR(255) COMMENT 'webdav的登录认证',
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ;